### ISSUE TITLE
Method for compiling TrombLoader for the Unity Editor

### ISSUE THREAD

**Issue by DerpyChap** [tc-mods/TrombLoader#14]
The version of TrombLoader shipped with the trombbackground template is a stripped down version with only the `Data` classes (and `Helpers`, if including more up to date builds distributed on the Discord). It also removes all dependencies outside of LeanTween, making distribution far more convenient.

Ideally, this could be facilitated via a build flag, but maintaining a separate fork could also work fine. Alternatively, the relevant scripts could be included in the Unity project directly instead of compiling a DLL.

**Comment by hedgehog1029** [comment]
Completed by #16
